// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import 'dotenv/config';
import { defineConfig } from 'prisma/config';
import { listLocalDatabases } from '@prisma/adapter-d1';

export default defineConfig({
	schema: 'api/prisma/schema.prisma',
	migrations: {
		path: 'api/prisma/migrations',
	},
	datasource: {
		url: `file://${listLocalDatabases().pop()}`,
	},
});
